version: "2"
services:
    qa:
        image: daocloud.io/quantaxis/qacommunity:latest
        container_name: qacommunity
        depends_on:
            - mgdb
            - qaeventmq
        ports:
            - "8888:8888"
            - "81:80"
        environment:
            - TZ=Asia/Shanghai
            - LANG=C.UTF-8
            - MONGODB=mgdb
            - QARUN=qaweb
            - QAPUBSUB_IP=qaeventmq
            - QAPUBSUB_PORT=5672
            - QAPUBSUB_USER=admin
            - QAPUBSUB_PWD=admin
        volumes:
            - qacode:/home
        restart: always
        networks:
            qanetwork:
                ipv4_address: 172.19.0.3

    # qacron:
    #     image: barretthugh/qa-cron
    #     environment:
    #         - MONGODB=mgdb
    #     restart: always

    qaweb_run:
        image: daocloud.io/quantaxis/qarun:latest
        container_name: qarun
        depends_on:
            - mgdb
            - qaeventmq
        ports:
            - "8010:8010"
        environment:
            - MONGODB=mgdb
            - QAPUBSUB_IP=qaeventmq
            - QAPUBSUB_PORT=5672
            - QAPUBSUB_USER=admin
            - QAPUBSUB_PWD=admin
            - QARUN_AMQP=pyamqp://admin:admin@qaeventmq:5672//
            - TZ=Asia/Shanghai
        restart: always
        depends_on:
          - qaeventmq
          - mgdb
        command: ['/root/wait_for_it.sh', 'qaeventmq:15672', '--' , "/root/runcelery.sh"]
        networks:
            qanetwork:
                ipv4_address: 172.19.0.4

    mgdb:
        image: daocloud.io/quantaxis/qamongo_single:latest
        ports:
            - "27017:27017"
        environment:
            - TZ=Asia/Shanghai
            - MONGO_INITDB_DATABASE=quantaxis
        volumes:
            - qamg:/data/db
        networks:
            qanetwork:
                ipv4_address: 172.19.0.2
        restart: always

    qaeventmq:
        image: daocloud.io/quantaxis/qaeventmq:latest
        ports:
            - "15672:15672"
            - "5672:5672"
            - "4369:4369"
        environment:
            - TZ=Asia/Shanghai
        networks:
            qanetwork:
                ipv4_address: 172.19.0.5
        restart: always

    qamonitor:
        image: daocloud.io/quantaxis/qa-monitor:latest
        ports:
            - "61209:61209"
            - "61208:61208"
        pid: "host"
        networks:
            qanetwork:
                ipv4_address: 172.19.0.6

        restart: always

    qactpbeebroker:
        image: daocloud.io/quantaxis/qactpbeebroker:latest
        ports:
            - "5000:5000"
        networks:
            qanetwork:
                ipv4_address: 172.19.0.7

            # --userid TEXT
            # --password TEXT
            # --brokerid TEXT
            # --mdaddr TEXT
            # --tdaddr TEXT
            # --appid TEXT
            # --authcode TEXT

        command: ['/root/wait_for_it.sh', 'qaeventmq:15672', '--' , "QACTPBEE", "--userid", "133496", "--password", 'QCHL1234']

    qamarketcollector:
        image: daocloud.io/quantaxis/qarealtimecollector:latest
        ports:
            - "8011:8011"
        depends_on:
            - mgdb
            - qaeventmq
        environment:
            - MONGODB=mgdb
            - EventMQ_IP=qaeventmq
        networks:
            qanetwork:
                ipv4_address: 172.19.0.8
        command:
            ['/root/QUANTAXIS_RealtimeCollector/docker/wait_for_it.sh', 'qaeventmq:5672', '--' ,'/root/QUANTAXIS_RealtimeCollector/docker/start_collector.sh']

            
    # qamarketcollector:
    #     image: daocloud.io/quantaxis/qamarket-rs:latest
    #     depends_on:
    #         - mgdb
    #         - qaeventmq
    #     environment:
    #         - MONGODB=mgdb
    #         - EventMQ_IP=qaeventmq
    #     networks:
    #         qanetwork:
    #             ipv4_address: 172.19.0.8

    qatrader:
        image: daocloud.io/quantaxis/qatrader:latest
        ports:
            - "8020:8020"
        depends_on:
            - mgdb
            - qaeventmq
        environment:
            - MONGODB=mgdb
            - QAPUBSUB_IP=qaeventmq
            - QAPUBSUB_PORT=5672
            - QAPUBSUB_USER=admin
            - QAPUBSUB_PWD=admin
            - QARUN_AMQP=pyamqp://admin:admin@qaeventmq:5672//
            - TZ=Asia/Shanghai
        command:
            ['/root/QATrader/docker/wait_for_it.sh', 'qaeventmq:5672', '--' ,'qatraderserver']

        networks:
            qanetwork:
                ipv4_address: 172.19.0.9


    editer:
        image: daocloud.io/quantaxis/qaeditor:latest
        container_name: qaeditor
        networks: 
            qanetwork:
                ipv4_address: 172.19.0.14
        ports: 
            - "3001:3000"
        environment:
            - TZ=Asia/Shanghai
            - LANG=C.UTF-8
            - MONGODB=mgdb
            - QARUN=qaweb
            - QAPUBSUB_IP=qaeventmq
            - QAPUBSUB_PORT=5672
            - QAPUBSUB_USER=admin
            - QAPUBSUB_PWD=admin
        restart: always
        volumes: 
            - qacode:/home/project


volumes:
    qamg:
        external:
            name: qamg
    qacode:
        external:
            name: qacode
networks:
    qanetwork:
        ipam:
            config:
                - subnet: 172.19.0.0/24
                  gateway: 172.19.0.1
